version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:16.14-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}

      - run: yarn run lint
      - run: yarn test
